background_opacity          0.6
cursor_trail                1
window_padding_width        25

remember_window_size no

font_family      Lato Regular
bold_font        Lato Bold
italic_font      Lato Italic
bold_italic_font Lato Bold Italic
font_size        11.0
